"""empty message

Revision ID: 7a7b5651ee5f
Revises: 
Create Date: 2023-09-22 18:54:26.259055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a7b5651ee5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('post_film',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('Ifilm', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('data', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_film')
    op.drop_table('admin')
    # ### end Alembic commands ###
