"""empty message

Revision ID: 8f3e2188bfec
Revises: 7a7b5651ee5f
Create Date: 2023-09-29 19:25:40.944520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f3e2188bfec'
down_revision = '7a7b5651ee5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('post_film', schema=None) as batch_op:
        batch_op.drop_column('Ifilm')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Ifilm', sa.VARCHAR(), nullable=False))

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
