"""empty message

Revision ID: 73d47a7b230d
Revises: 8f3e2188bfec
Create Date: 2023-10-02 19:39:12.145988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d47a7b230d'
down_revision = '8f3e2188bfec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_film', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
